 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.charlware.ants.ui;

import com.charlware.ants.AntHome;
import com.charlware.ants.World;
import com.charlware.ants.sim.RandomFoodGenerator;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author CVanJaarsveldt
 */


public class SimAnt extends javax.swing.JFrame implements SimulationStepListener {

    private World world = null;
    private WorldPanel pnlWorld = null;
    private int numSteps = 0;
    private EventLogFrame eventLogFrame = null;

    /**
     * Creates new form SimAnt
     */
    public SimAnt() {
        initWorld();

        initComponents();

        initBoard();

        initPlugins();

        setDefaults();

        eventLogFrame = new EventLogFrame(this);
        eventLogFrame.setVisible(true);
        eventLogFrame.setLocationRelativeTo(this);
    }

    private void initWorld() {
        world = new World(30);
    }

    private void initBoard() {
        pnlWorld = new WorldPanel(world);
        pnBoardScrollPane.setViewportView(pnlWorld);
        pnlWorld.addStepListener(this);

        StatsModel model = new StatsModel(world);
        tbStats.setModel(model);

        tbStats.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                System.out.println("Selecting: " + e.toString());
                if(!e.getValueIsAdjusting()) {
                    int selectedHome = tbStats.getSelectedRow();
                    if(selectedHome >= 0) {
                        AntHome antHome = model.getAntHome(selectedHome);
                        System.out.println("AntHome: " + antHome.getId());
                        pnlWorld.setHighlightedAntHome(antHome);
                    }
                }
            }
        });

        pack();
        revalidate();
    }

    public World getWorld() {
        return world;
    }

    private void setDefaults() {
        spNumFoodSources.setValue(100);
        spNumFoodSourcesStateChanged(null);
    }

    private void initPlugins() {
        pnlWorld.addStepListener(new RandomFoodGenerator(world));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgFileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txSteps = new javax.swing.JTextField();
        txAnts = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txAntHomes = new javax.swing.JTextField();
        pnBoardScrollPane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spNumFoodSources = new javax.swing.JSpinner();
        btStart = new javax.swing.JButton();
        btAddTempFoodSource = new javax.swing.JButton();
        spnSpeed = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStats = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSaveSimSettings = new javax.swing.JMenuItem();
        mnuOpenSimSettings = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ant Simulator");

        jLabel1.setText("Steps:");

        jLabel2.setText("Ants:");

        txSteps.setEditable(false);

        txAnts.setEditable(false);

        jLabel3.setText("AntHomes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txAntHomes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txAnts, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txAntHomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txAnts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBoardScrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnBoardScrollPane.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Stable Foodsources:");

        spNumFoodSources.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spNumFoodSourcesStateChanged(evt);
            }
        });

        btStart.setText("Start");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        btAddTempFoodSource.setText("Drop Temp Foodsource");
        btAddTempFoodSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTempFoodSourceActionPerformed(evt);
            }
        });

        spnSpeed.setModel(new javax.swing.SpinnerListModel(new String[] {"x1", "x2", "x4", "x8", "x16"}));
        spnSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSpeedStateChanged(evt);
            }
        });

        jLabel5.setText("Speed:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spNumFoodSources, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddTempFoodSource, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btStart, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spNumFoodSources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btStart)
                    .addComponent(btAddTempFoodSource))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbStats);

        jMenu1.setMnemonic('F');
        jMenu1.setText("Sim Ant");

        mnuSaveSimSettings.setText("Save Sim Settings...");
        mnuSaveSimSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaveSimSettingsActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSaveSimSettings);

        mnuOpenSimSettings.setText("Open Sim Settings...");
        mnuOpenSimSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenSimSettingsActionPerformed(evt);
            }
        });
        jMenu1.add(mnuOpenSimSettings);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnBoardScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBoardScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        if(btStart.getText().equals("Start")) {
            pnlWorld.start();
            btStart.setText("Stop");
        } else {
            pnlWorld.stop();
            btStart.setText("Start");
        }
    }//GEN-LAST:event_btStartActionPerformed

    private void spNumFoodSourcesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spNumFoodSourcesStateChanged
        int currentFoodSources = world.getFoodSources().size();
        int newFoodSources = (int) spNumFoodSources.getValue();
        int diff = newFoodSources - currentFoodSources;
        if(diff < 0) {
            world.removeStableFoodSources(Math.abs(diff));
        } else if(diff > 0) {
            world.addStableFoodSources(diff);
        }
    }//GEN-LAST:event_spNumFoodSourcesStateChanged

    private void btAddTempFoodSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTempFoodSourceActionPerformed
        world.addTempFoodSource();
        spNumFoodSources.setValue(world.getFoodSources().size());
    }//GEN-LAST:event_btAddTempFoodSourceActionPerformed

    private void spnSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSpeedStateChanged
        int multiplier;
        switch(spnSpeed.getValue().toString()) {
            case "x1":
                multiplier = 1;
                break;
            case "x2":
                multiplier = 2;
                break;
            case "x4":
                multiplier = 4;
                break;
            case "x8":
                multiplier = 8;
                break;
            case "x16":
                multiplier = 16;
                break;
            default:
                multiplier = 1;
        }
        pnlWorld.setSpeedMultiplier(multiplier);
    }//GEN-LAST:event_spnSpeedStateChanged

    private void mnuOpenSimSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenSimSettingsActionPerformed
        if(dlgFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                getWorld().getSimSettings().load(dlgFileChooser.getSelectedFile().getAbsolutePath());
            } catch(IOException ex) {
                JOptionPane.showMessageDialog(this, "Error reading file: " + ex, "Error reading file", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_mnuOpenSimSettingsActionPerformed

    private void mnuSaveSimSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaveSimSettingsActionPerformed
        if(dlgFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                getWorld().getSimSettings().save(dlgFileChooser.getSelectedFile().getAbsolutePath());
            } catch(IOException ex) {
                JOptionPane.showMessageDialog(this, "Error saving file: " + ex, "Error saving file", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mnuSaveSimSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimAnt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddTempFoodSource;
    private javax.swing.JButton btStart;
    private javax.swing.JFileChooser dlgFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuOpenSimSettings;
    private javax.swing.JMenuItem mnuSaveSimSettings;
    private javax.swing.JScrollPane pnBoardScrollPane;
    private javax.swing.JSpinner spNumFoodSources;
    private javax.swing.JSpinner spnSpeed;
    private javax.swing.JTable tbStats;
    private javax.swing.JTextField txAntHomes;
    private javax.swing.JTextField txAnts;
    private javax.swing.JTextField txSteps;
    // End of variables declaration//GEN-END:variables

    @Override
    public void simulationStepped() {
        txSteps.setText("" + (++numSteps));
        txAnts.setText("" + world.getAnts().size());
        txAntHomes.setText("" + world.getAntHomes().size());
    }
}
